# TODO: Get paginator working in /blog/ subdirectory.
# TODO: Get permalinks to work as /blog/:title/.

# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /blog/:title/

# Setup
title:            MightyMap
tagline:          'One-click mapping'
description:      'Make a map in one click. Just select a spreadsheet we&apos;ll do the rest.'
url:              http://mightymap.github.io

author:
  name:           'Brad Simantel'
  url:            https://twitter.com/mightymap

paginate:         5
paginate_path:    /blog/:num/